version: '3.7'

services:
  db:
    image: postgis:14-3.2
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=doitwebdev01
    ports:
      - '5432:5432'
    volumes:
      - /home/elCamino/db
  web:
    image: node:16
    user: "node"
    working_dir: /home/docker/elCamino/web
    environment:
      - NODE_ENV=development
    volumes:
      -  /home/node/elCamino/web
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: "npm start"
