version: '3.4'

services:
  node:
    image: node:16
    user: "node"
    working_dir: /home/node/elCamino
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/elCamino
    ports:
      - "3000:3000"
    command: "npm start"