version: '3.7'

services:
  db:
    image: 'postgis/postgis:14-3.2'
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=doitwebdev01
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: ./web
    ports:
      - '5000:5000'

volumes:
  db_data: