version: '3.4'

services:
  node:
    image: node:lts
    user: "node"
    working_dir: /home/node/elCamino
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/elCamino
    expose:
      - "3000"
    command: "npm start"