# Node base image, ca be replaced with node:(version), eg. node:16
# More node tags on Node's DockerHub: https://hub.docker.com/_/node
FROM node:lts
# 'Expose' port 3000, Node's default port
EXPOSE 3000